services:
  - type: web
    name: student-management
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false   # Render will keep this secret, you must set it manually
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://student-management.onrender.com

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_RENDER_DB_HOST    # e.g. mysql-xxxx.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: YOUR_RENDER_DB_NAME
      - key: DB_USERNAME
        value: YOUR_RENDER_DB_USER
      - key: DB_PASSWORD
        value: YOUR_RENDER_DB_PASSWORD
