services:
  - type: web
    name: student-management
    env: php
    plan: free 
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:1znjJ0aRyP0ldJZl4iO58qObLPh0wIGtSCYcNaUxmWY=
      - key: APP_URL
        value: https://your-render-domain.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-db-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-db-name>
      - key: DB_USERNAME
        value: <your-db-user>
      - key: DB_PASSWORD
        value: <your-db-password>
